---
- name: Configure MOTD banner
  hosts: routers
  gather_facts: no

  tasks:
    - name: Configure banner motd using env MOTD
      cisco.ios.ios_config:
        lines:
          - "banner motd ^{{ lookup('env','MOTD') }}^"
      when: lookup('env','MOTD') is not none
      delegate_to: localhost
